### ISSUE TITLE
Migrating from 0.1.0 to 0.2.0

### ISSUE THREAD

**Issue by tomj74** [rvinzent/django-dynamic-models#22]
0.2.0 looks like a nice refactor, some things got a lot simpler.

One Q -- How do you propose we migrate an existing app from 0.1.0 to 0.2.0?

The migration that creates the modelschema and fieldschema tables in 0.2.0 is numbered 0001 BUT my app was already using 0.1.0, so it never runs the new 0001 from 0.2.0 since the migration system believes that it has already run the 0001 migration from the dynamic_models app (because it already did, back when it was deployed with 0.1.0 which had a different 0001 migration).

Perhaps a new app name would have been appropriate?  ie to avoid potential for this sort of conflict.

**Comment by tomj74** [comment]
In the end, I had to temporarily add this to our deploy script
```
python manage.py migrate --fake dynamic_models zero
```
and manually drop the the left-over dynamic_models_modelfieldschema table

**Comment by rvinzent** [comment]
Hi @tomj74,

I don't have any sort of expectation to maintain backwards compatibility pre-1.0, but I think the tables will generally be more stable going forward, so I hope this will be the most painful migration .

I thought it might be cleaner to wipe the slate clean and start with new migrations given 0.1 and 0.2 versions are so different from a schema point of view.

Thanks for sharing your fix and I'll try to be more conscious of migration strategies in the future 🙂

**Comment by rvinzent** [comment]
Closing this, as we are now a few versions ahead. The legacy documentation can be found [here](https://github.com/rvinzent/django-dynamic-models/wiki/Legacy). Apologies again for the largely incompatible schemas between `v0.1.0` and `v0.2.0`.
