### ISSUE TITLE
OutdatedModelError

### ISSUE THREAD

**Issue by jingyi-xie** [rvinzent/django-dynamic-models#23]
I keep getting this error anytime I make a slight change to my code.
I found in the previous version's document that "Be sure to grab the latest version of the dynamic model after changing schema or OutdatedModelError will be raised on save."
I tried to avoid using `save()` and only use `get_or_create()` but still got the same error.

**Comment by rvinzent** [comment]
@jingyi-xie are you able to paste your code or a minimal reproduction of the error?

**Comment by jingyi-xie** [comment]
Sure. Let's say I want to create a model called `Example`. I use the following code to have access to the model
```python
def getOrCreateExample():
    # Check if the table already exists.
    # If already exists, return the model directly
    if len(ModelSchema.objects.filter(name='example')) == 1:
        return ModelSchema.objects.get(name='example').as_model()

    # If the table doesn't exist yet, create the table and return the model
    example_schema = ModelSchema.objects.create(name='example')
    name_field = FieldSchema.objects.create(model_schema=example_schema, name='name', data_type='character')
    return course_schema.as_model()
```
Then I use the following
```python
Example = getOrCreateExample()
Example.objects.get_or_create(name='example_name')
```
I always get `OutdatedModelError` on the `get_or_create()` when I change the code elsewhere.

**Comment by rvinzent** [comment]
hmm I am unable to reproduce the issue with your code. Can you please update with your Django version and your type of database backend?

> when I change the code elsewhere

can you elaborate on that? how does the code change elsewhere? it could be the source of the issue.

One small thing that may help your code.you can use `get_or_create()` to create the model schema object.
```python
def get_or_create_example_model():
    example_schema, created = ModelSchema.objects.get_or_create(name='example')
    if created:
        FieldSchema.objects.create(
            model_schema=example_schema,
            name='name',
            data_type='character'
       )
    return example_schema.as_model()
```

**Comment by jingyi-xie** [comment]
Thanks for your reply. I use Django 3.0.6 and the built-in SQLite database. I know only postgres is officially supported, so could this be the problem? Also, sorry for the confusion. 'Change the code elsewhere' means other code, not the one I posted.

**Comment by jingyi-xie** [comment]
I really appreciate your suggestion. I tried to use `get_or_create()` to create the model schema object but got the following error. It seems that it has something to do with sqlite.

> SQLite schema editor cannot be used while foreign key constraint checks are enabled. Make sure to disable them before entering a transaction.atomic() context because SQLite does not support disabling them in the middle of a multi-statement transaction.

**Comment by rvinzent** [comment]
> I really appreciate your suggestion. I tried to use `get_or_create()` to create the model schema object but got the following error. It seems that it has something to do with sqlite.
> 
> > SQLite schema editor cannot be used while foreign key constraint checks are enabled. Make sure to disable them before entering a transaction.atomic() context because SQLite does not support disabling them in the middle of a multi-statement transaction.

Yea that sounds like something in SQLite. Is this call happening inside of a `transaction`? Some databases disallow DDL statements inside of transactions.

**Comment by jingyi-xie** [comment]
I changed the database to postgres but still got the OutdatedModelError.
