### ISSUE TITLE
retrieval

### ISSUE THREAD

**Issue by morysam96** [rvinzent/django-dynamic-models#29]
hi 
I want to call the model of the car made, how to do it

**Comment by rvinzent** [comment]
Hi, @morysam96

please refer to the [wiki](https://github.com/rvinzent/django-dynamic-models/wiki/ModelSchema) for examples, and if you have any additional questions, examples of your code will be useful to help answer them. 

Thanks!

**Comment by rvinzent** [comment]
Feel free to re-open if you still have questions after going through the documentation.
