### ISSUE TITLE
django.db.utils.OperationalError: no such table: dynamic_models_modelfieldschema

### ISSUE THREAD

**Issue by elterrien** [rvinzent/django-dynamic-models#6]
Hi,
I have installed django-dynamic-models and I'm following the documentation.

When I create a new object with the command :
`car_schema = ModelSchema.objects.create(name='car')`

 The command return an error : 
> no such table: dynamic_models_modelfieldschema

Have you ever encountered this error ?

**Comment by yvsssantosh** [comment]
Hi, I get the same error as well, please let me know if you have found a solution for that

**Comment by rvinzent** [comment]
Hi, if the docs could be clearer, please feel free to submit a PR with improved instructions. If not, I'll get around to it at some point :). @elterrien Did @yvsssantosh 's suggestion fix the issue?

**Comment by macieyn** [comment]
@rvinzent, @yvsssantosh suggestion worked for me.

**Comment by arpitremarkable** [comment]
migrations folder should be copied during `pip install django-dynamic-model`

**Comment by evangetrixx** [comment]
@yvsssantosh thanks a loooot, I was looking for this problem for a long time and then I found you
