### ISSUE TITLE
Release v0.4.0 on PyPI

### ISSUE THREAD

**Issue by atodorov** [rvinzent/django-dynamic-models#67]
@rvinzent it's been a while since the latest upload to PyPI, https://pypi.org/project/django-dynamic-model/#history. 

Do you mind pushing the latest release ?

**Comment by rvinzent** [comment]
@atodorov sure I can work on it soon. I think there was a couple of things left to take care of and I never got around to it

**Comment by rvinzent** [comment]
@atodorov I'll release a candidate first #70  to see if it fits your use case. There's still a known bug #58 , and the docs in the wiki don't include the latest changes #69

**Comment by rvinzent** [comment]
[v0.4.0rc0](https://pypi.org/project/django-dynamic-model/0.4.0rc0/) has been released! Please test out your use case and open an issue for any bugs you might come across. Thanks!
